version: "3.8"

services:
  laravel:
    build: ./php
    volumes:
      - ./laravel:/var/www

  nginx:
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./laravel:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
